# Generated by Django 5.0.6 on 2024-05-28 08:28

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcomment_like'),
    ]
    operations = [
    ]