# Generated by Django 5.0.6 on 2024-05-28 08:44

from django.db import migrations
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240528_1528'),
    ]
    
    operations = [
    ]

   
