# Generated by Django 5.0.6 on 2024-05-28 13:05

from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240528_1544'),
    ]

    def create_default_data(apps, schema_editor):
        Category = apps.get_model('products', 'Category')
        Product = apps.get_model('products', 'Product')
        
        category_data = [
	            "Full House / Combo Phòng",
                "Combo Phòng",                
                "Bàn",
	            "Set Tủ / Bàn" ,                          
                "Ghế",
                "Tủ",
                "Giường",
                "Kệ",                
                "Bộ Bàn Ăn",
                "Hộc"
        ] 
        product_data = [
            {
                "category": "Ghế",
                "productName": "Ghế Sofa Gỗ Tràm Tự Nhiên MOHO VLINE 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ghe_sofa_go_vline_dem_be_1_810c604bcf444eb095ef1546816221bc_grande.jpg",
                "price": 7490000,
                "rating": 4.97,
                "reviewCount": 32,
                "boughtCount": 492,
                "discount": 35
            },
            {
                "category": "Giường",
                "productName": "Giường Ngủ Gỗ Tràm MOHO VLINE 601 Nhiều Kích Thước",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_giuong_ngu_go_tram_vline_1m8_1_5211e7d2a3da44f58070de291c446400_grande.jpg",
                "price": 4490000,
                "rating": 4.93,
                "reviewCount": 34,
                "boughtCount": 860,
                "discount": 44
            },
            {
                "category": "Tủ",
                "productName": "Tủ Đầu Giường Gỗ MOHO VLINE 801",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_dau_giuong_vline_801_3_e4a191da342a421592e66dbde854ab8a_grande.jpg",
                "price": 1990000,
                "rating": 5,
                "reviewCount": 10,
                "boughtCount": 429,
                "discount": 20
            },
            {
                "category": "Kệ",
                "productName": "Kệ Gỗ – Kệ Sách MOHO OSLO 901",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_ke_sach_oslo_1_f79051e471794a8898e67db56b0aa26a_grande.jpg",
                "price": 1690000,
                "rating": 4.91,
                "reviewCount": 39,
                "boughtCount": 500,
                "discount": 32
            },
            {
                "category": "Ghế",
                "productName": "Ghế Sofa Gỗ Cao Su Tự Nhiên MOHO HOBRO 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ghe_sofa_go_moho_hobro_3_22217ef0e9b249ba8a4d365613051c0d_grande.jpg",
                "price": 10990000,
                "rating": 5,
                "reviewCount": 3,
                "boughtCount": 26,
                "discount": 31
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set Tủ Quần Áo MOHO HOBRO 301 3 Cánh Ngăn Kệ",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_quan_ao_hobro_3_canh_1m5_26_c198c0aeae2848bc95511760e1566899_grande.png",
                "price": 10490000,
                "rating": 5,
                "reviewCount": 2,
                "boughtCount": 21,
                "discount": 38
            },
            {
                "category": "Ghế",
                "productName": "Ghế Ăn Gỗ Cao Su Tự Nhiên MOHO NEXO 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_cam_dat_ghe_an_go_cao_su_tu_nhien_nexo_5_c9157e6776b3472ab8d4447e41600fb1_grande.jpg",
                "price": 1190000,
                "rating": 5,
                "reviewCount": 7,
                "boughtCount": 100,
                "discount": 40
            },
            {
                "category": "Ghế",
                "productName": "Ghế Ăn Gỗ Cao Su Tự Nhiên MOHO OSLO 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ghe_an_oslo_dem_xam_6_b8922c5413504a1b9796513aa9ae7e05_grande.jpg",
                "price": 1090000,
                "rating": 5,
                "reviewCount": 18,
                "boughtCount": 810,
                "discount": 45
            },
            {
                "category": "Bàn",
                "productName": "Bàn Làm Việc Gỗ MOHO FYN 601 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ban_lam_viec_go_fyn_1_eb59119826ec430088f791766ece564c_grande.jpg",
                "price": 1990000,
                "rating": 5,
                "reviewCount": 8,
                "boughtCount": 139,
                "discount": 40
            },
            {
                "category": "Giường",
                "productName": "Giường Ngủ Gỗ Tràm MOHO DALUMD 301",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_giuong_ngu_go_dalumd_1m6_1_b6335d3cd4fd4c0f9c891772815100d5_grande.jpg",
                "price": 5290000,
                "rating": 5,
                "reviewCount": 14,
                "boughtCount": 222,
                "discount": 41
            },
            {
                "category": "Tủ",
                "productName": "Tủ Kệ Tivi Gỗ MOHO OSLO 201",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_ke_tivi_go_oslo__201_3_273e68b8cf4a4a2fa4a4866b937c73b9_grande.jpg",
                "price": 2290000,
                "rating": 5,
                "reviewCount": 78,
                "boughtCount": 874,
                "discount": 34
            },
            {
                "category": "Ghế",
                "productName": "Ghế Sofa Góc Chữ L Gỗ Cao Su Tự Nhiên MOHO VLINE 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ghe_sofa_vline_sofa_goc_be_2_5cf711b51ccc48d7902ee5a5d3ce8539_grande.jpg",
                "price": 11480000,
                "rating": 5,
                "reviewCount": 13,
                "boughtCount": 39,
                "discount": 40
            },
            {
                "category": "Ghế",
                "productName": "Ghế Sofa Gỗ Cao Su Tự Nhiên MOHO FYN 901",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ghe_sofa_fyn_901_2_913919888ddd4e10a79384ac3c15b107_grande.jpg",
                "price": 11990000,
                "rating": 5,
                "reviewCount": 18,
                "boughtCount": 118,
                "discount": 27
            },
            {
                "category": "Tủ",
                "productName": "Tủ Quần Áo Gỗ 2 Cánh MOHO VIENNA 201 4 Màu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_tu_quan_ao_vienna_201_2_a08430a02a7f4b40bfe217016f4fbac8_grande.png",
                "price": 5290000,
                "rating": 4.93,
                "reviewCount": 52,
                "boughtCount": 580,
                "discount": 29
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set Tủ Quần Áo Gỗ MOHO VLINE 601 3 Cánh",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_tu_quan_ao_vline_1_1__81f8232b0d4f40ba89954fb956330511_grande.png",
                "price": 9490000,
                "rating": 5,
                "reviewCount": 18,
                "boughtCount": 82,
                "discount": 37
            },
            {
                "category": "Bàn",
                "productName": "Bàn Sofa - Bàn Cafe - Bàn Trà Gỗ Thông MOHO VLINE 501",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ban_sofa_ban_tra_ban_cafe_go_vline_501_b40d5fef047245db895a9dbc7defa6df_grande.jpg",
                "price": 1390000,
                "rating": 4.96,
                "reviewCount": 25,
                "boughtCount": 481,
                "discount": 44
            },
            {
                "category": "Bàn",
                "productName": "Bàn Làm Việc Gỗ MOHO WORKS 701",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_trang_noi_that_moho_ban_lam_viec_work_701_1m4_5_5defdced630e4f2e9016abe77a1ea1e5_grande.jpg",
                "price": 1490000,
                "rating": 5,
                "reviewCount": 15,
                "boughtCount": 285,
                "discount": 40
            },
            {
                "category": "Giường",
                "productName": "Giường Ngủ Gỗ Tràm MOHO MALAGA 302 Nhiều Kích Thước",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_giuong_ngu_go_tram_malaga_302_12_b323fac7406b42e8bfc0f7dae9fa0861_grande.jpg",
                "price": 4290000,
                "rating": 5,
                "reviewCount": 31,
                "boughtCount": 311,
                "discount": 28
            },
            {
                "category": "Ghế",
                "productName": "Ghế Ăn Gỗ Cao Su Tự Nhiên MOHO FYN",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ghe_an_go_fyn_1_ce95b219df3e41cca26fcc19204802e5_grande.jpg",
                "price": 1590000,
                "rating": 5,
                "reviewCount": 7,
                "boughtCount": 564,
                "discount": 27
            },
            {
                "category": "Tủ",
                "productName": "Tủ Đầu Giường Gỗ MOHO VIENNA 201",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_tu_dau_giuong_vienna_1_ec62678e4488474cbe84fe001dfd1d6d_grande.jpg",
                "price": 1290000,
                "rating": 5,
                "reviewCount": 23,
                "boughtCount": 405,
                "discount": 19
            },
            {
                "category": "Kệ",
                "productName": "Kệ Để Sách 5 Tầng MOHO WORKS 701",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_trang_noi_that_moho_ke_de_sach_5_tang_moho_works_8_0fceadbecd0d48df9113163674a088b9_grande.jpg",
                "price": 2490000,
                "rating": 5,
                "reviewCount": 6,
                "boughtCount": 82,
                "discount": 48
            },
            {
                "category": "Ghế",
                "productName": "Ghế Ăn Gỗ Cao Su Tự Nhiên MOHO ODESSA",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ghe_an_go_odessa_7_39298378f71a4db6a4a1d23f838584c3_grande.jpg",
                "price": 1190000,
                "rating": 5,
                "reviewCount": 18,
                "boughtCount": 534,
                "discount": 40
            },
            {
                "category": "Giường",
                "productName": "Giường Ngủ Gỗ Tràm MOHO MALAGA 301 V2",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_giuong_ngu_go_malaga_301_1m6_1_852435d386774636a7f9e9c6384e45d9_grande.jpg",
                "price": 5490000,
                "rating": 5,
                "reviewCount": 29,
                "boughtCount": 628,
                "discount": 39
            },
            {
                "category": "Ghế",
                "productName": "Ghế Sofa Gỗ Cao Su Tự Nhiên MOHO FIJI 401",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ghe_sofa_go_fiji_1_e962937714bb42b4b8c5d31c72123940_grande.jpg",
                "price": 9990000,
                "rating": 5,
                "reviewCount": 13,
                "boughtCount": 94,
                "discount": 31
            },
            {
                "category": "Tủ",
                "productName": "Tủ Quần Áo Gỗ MOHO VLINE 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_tu_quan_ao_vline_601_52cm_5_1__e4782a62d42545d2a74d2643af3b8058_grande.png",
                "price": 3490000,
                "rating": 5,
                "reviewCount": 33,
                "boughtCount": 380,
                "discount": 36
            },
            {
                "category": "Ghế",
                "productName": "Ghế Ăn Gỗ Cao Su Tự Nhiên MOHO VLINE 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ghe_an_vline_1_d3141504a3164161ab891983182514b1_grande.jpg",
                "price": 1290000,
                "rating": 5,
                "reviewCount": 21,
                "boughtCount": 810,
                "discount": 35
            },
            {
                "category": "Giường",
                "productName": "Giường Ngủ Gỗ MOHO VLINE 601 Nhiều Kích Thước",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_giuong_ngu_go_soi_vline_601_6_33bb4e7536c548e1bfda6e56681d4c59_grande.jpg",
                "price": 4490000,
                "rating": 4.93,
                "reviewCount": 33,
                "boughtCount": 767,
                "discount": 44
            },
            {
                "category": "Ghế",
                "productName": "Ghế Sofa Gỗ Tràm Tự Nhiên MOHO KOLDING 701",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ghe_sofa_go_kolding_2m_6_d3e3051f0be24df6bb8d9ffd75a2eb7f_grande.jpg",
                "price": 5000000,
                "rating": 5,
                "reviewCount": 10,
                "boughtCount": 66,
                "discount": 41
            },
            {
                "category": "Bàn",
                "productName": "Bàn Sofa – Bàn Cafe – Bàn Trà Gỗ MOHO OSLO 901",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_nau_noi_that_moho_ban_sofa_oslo_6_14bae974e064425da9300e562dcfafc6_grande.jpg",
                "price": 1290000,
                "rating": 5,
                "reviewCount": 26,
                "boughtCount": 503,
                "discount": 41
            },
            {
                "category": "Ghế",
                "productName": "Ghế Sofa Gỗ Cao Su Tự Nhiên MOHO VLINE 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ghe_sofa_go_vline_1_6fd2522f70c04d5fbd326e587f30ddb7_grande.jpg",
                "price": 7490000,
                "rating": 4.88,
                "reviewCount": 35,
                "boughtCount": 442,
                "discount": 35
            },
            {
                "category": "Bàn",
                "productName": "Bàn Sofa – Bàn Cafe – Bàn Trà Tròn Gỗ MOHO OSLO 901",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_ban_tra_sofa_go_tron_oslo_1_263a4ddc3999406b8c3ad6fe4120b654_grande.jpg",
                "price": 1290000,
                "rating": 5,
                "reviewCount": 25,
                "boughtCount": 420,
                "discount": 48
            },
            {
                "category": "Tủ",
                "productName": "Tủ Quần Áo Gỗ Kệ Ngăn MOHO VIENNA 201 4 Màu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_tu_quan_ao_vienna_ke_ngan_4_mau_1_d20e0536701e44f884fb79d0a459df1f_grande.jpg",
                "price": 3990000,
                "rating": 5,
                "reviewCount": 15,
                "boughtCount": 389,
                "discount": 11
            },
            {
                "category": "Bàn",
                "productName": "Bàn Làm Việc Gỗ MOHO VLINE 601 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ban_lam_viec_vline_601_1_audit_faa97ffd0bcb4a0aa4a68b450901e608_grande.jpg",
                "price": 1590000,
                "rating": 4.88,
                "reviewCount": 25,
                "boughtCount": 393,
                "discount": 47
            },
            {
                "category": "Tủ",
                "productName": "Tủ Giày – Tủ Trang Trí Gỗ MOHO OSLO 901",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_tu_giay_oslo_901_4_aa6deab03e374e7c8417afa33c8d70ec_grande.jpg",
                "price": 2190000,
                "rating": 4.91,
                "reviewCount": 24,
                "boughtCount": 378,
                "discount": 37
            },
            {
                "category": "Ghế",
                "productName": "Ghế Ăn Gỗ Cao Su Tự Nhiên MOHO MILAN 601 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_ghe_an_go_milan_1_ac2aae2b06094ab595210f7bcdb0e47f_grande.jpg",
                "price": 1390000,
                "rating": 5,
                "reviewCount": 10,
                "boughtCount": 372,
                "discount": 30
            },
            {
                "category": "Ghế",
                "productName": "Ghế Băng Dài Gỗ Cao Su Tự nhiên MOHO VLINE 602",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ghe_bang_vline_1_4397fc25ea9a4bdc96761186e1c88adc_grande.jpg",
                "price": 1390000,
                "rating": 4.85,
                "reviewCount": 14,
                "boughtCount": 338,
                "discount": 33
            },
            {
                "category": "Ghế",
                "productName": "Ghế Ăn Gỗ Cao Su Tự Nhiên MOHO MILAN 601 Màu Gỗ",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ghe_an_go_milan_1_91168f57e14c4b13abab1a297c8c4172_grande.jpg",
                "price": 1390000,
                "rating": 5,
                "reviewCount": 9,
                "boughtCount": 311,
                "discount": 30
            },
            {
                "category": "Tủ",
                "productName": "Tủ Kệ Tivi Gỗ Tràm MOHO VLINE 301",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_ke_tivi_vline_1_6f199eeb82c04d3bac2d13441410a04c_grande.jpg",
                "price": 2990000,
                "rating": 4.79,
                "reviewCount": 51,
                "boughtCount": 319,
                "discount": 40
            },
            {
                "category": "Bàn",
                "productName": "Bàn Làm Việc Gỗ MOHO VLINE 601 Màu Tự Nhiên",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ban_lam_viec_vline_1_2ffbfab94fa748a99e6f4c24bb6a00d9_grande.jpg",
                "price": 1590000,
                "rating": 5,
                "reviewCount": 24,
                "boughtCount": 305,
                "discount": 47
            },
            {
                "category": "Ghế",
                "productName": "Ghế Băng Tựa Gỗ Cao Su Tự nhiên MOHO VLINE 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ghe_bang_dai_vline_1_072a458d988f4a77a56a210258fe0a51_grande.jpg",
                "price": 1890000,
                "rating": 5,
                "reviewCount": 15,
                "boughtCount": 310,
                "discount": 35
            },
            {
                "category": "Tủ",
                "productName": "Tủ Đầu Giường Gỗ MOHO VLINE 801 Màu Tự Nhiên",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_tu_dau_giuong_vline_1_9153ef95eb024e4ab35bbfce46902d47_grande.jpg",
                "price": 1990000,
                "rating": 5,
                "reviewCount": 5,
                "boughtCount": 298,
                "discount": 20
            },
            {
                "category": "Tủ",
                "productName": "Tủ Quần Áo Gỗ Thanh Treo MOHO VIENNA 201 4 Màu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/an_ao_thanh_treo_vienna_201_1_87005e5958b04fe5a56725fdd9386f8f_large_1_f10eff8c27c045f1a07f323f2301fff1_grande.png",
                "price": 3990000,
                "rating": 4.93,
                "reviewCount": 15,
                "boughtCount": 283,
                "discount": 11
            },
            {
                "category": "Hộc",
                "productName": "Hộc Tủ 3 Ngăn Lưu Trữ Tài Liệu Có Khóa MOHO WORKS 201",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_trang_noi_that_moho_hoc_tu_luu_tru_11_7cac38416e714e32b8534fd2a8e011d8_grande.jpg",
                "price": 990000,
                "rating": 5,
                "reviewCount": 12,
                "boughtCount": 242,
                "discount": 48
            },
            {
                "category": "Bàn",
                "productName": "Bàn Sofa – Bàn Cafe – Bàn Trà Tròn Cao Gỗ MOHO OSLO 901",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ban_tra_tron_cao_oslo_1_85235a0421f74987a776f913a38c86b8_grande.jpg",
                "price": 590000,
                "rating": 5,
                "reviewCount": 14,
                "boughtCount": 249,
                "discount": 40
            },
            {
                "category": "Tủ",
                "productName": "Tủ Giày - Tủ Trang Trí Gỗ Tràm MOHO VLINE 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_giay_vline_601_1_3c16cf25f44b4e8b806ea944f6208851_grande.jpg",
                "price": 2490000,
                "rating": 5,
                "reviewCount": 27,
                "boughtCount": 265,
                "discount": 36
            },
            {
                "category": "Bàn",
                "productName": "Bàn Sofa - Bàn Cafe - Bàn Trà Gỗ MOHO VLINE 501",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ban_sofa_vline_501_1_0bdb9fe421b244b899ddcb7212a2474e_grande.jpg",
                "price": 1390000,
                "rating": 5,
                "reviewCount": 14,
                "boughtCount": 233,
                "discount": 44
            },
            {
                "category": "Bàn",
                "productName": "Bàn Ăn Gỗ Cao Su MOHO OSLO 901",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ban_an_go_oslo_1_356b08ca04f84e61bbb8d8a11c4e1732_grande.jpg",
                "price": 3790000,
                "rating": 5,
                "reviewCount": 9,
                "boughtCount": 225,
                "discount": 16
            },
            {
                "category": "Kệ",
                "productName": "Kệ Gỗ – Kệ Sách MOHO OSLO 902",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_ke_sach_oslo_902_1_6406ed833ec24335b4396a3edd0509a4_grande.jpg",
                "price": 1990000,
                "rating": 4.74,
                "reviewCount": 19,
                "boughtCount": 231,
                "discount": 29
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set Tủ Quần Áo Gỗ MOHO VIENNA 201 3 Cánh Kệ Ngăn 4 Màu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_tu_quan_ao_vienna_3_canh_1_d56e71335a664caebd06a3c75a42f7cb_grande.jpg",
                "price": 8290000,
                "rating": 5,
                "reviewCount": 22,
                "boughtCount": 222,
                "discount": 31
            },
            {
                "category": "Ghế",
                "productName": "Ghế Đôn Sofa Gỗ Cao Su Tự Nhiên MOHO VLINE 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_ghe_don_sofa_vline_dem_be_4_25293fd64e1146188437415b13cf2353_grande.jpg",
                "price": 1490000,
                "rating": 5,
                "reviewCount": 6,
                "boughtCount": 221,
                "discount": 42
            },
            {
                "category": "Ghế",
                "productName": "Ghế Xoay Văn Phòng Tay Gập Thông Minh MOHO RIGA 701",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_trang_noi_that_moho_ghe_van_phong_riga_1_92865499928b49a191bbf2d0e0c91f6f_grande.jpg",
                "price": 1190000,
                "rating": 5,
                "reviewCount": 9,
                "boughtCount": 211,
                "discount": 30
            },
            {
                "category": "Bàn",
                "productName": "Bàn Sofa – Bàn Cafe – Bàn Trà Gỗ Cao Su MOHO MILAN 601 Xám",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_xam_noi_that_moho_ban_sofa_verona_07_37e02ac56dd941388889956b65089a3a_grande.jpg",
                "price": 590000,
                "rating": 5,
                "reviewCount": 10,
                "boughtCount": 197,
                "discount": 9
            },
            {
                "category": "Ghế",
                "productName": "Ghế Văn Phòng Chân Xoay MOHO MAJOR 701",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_den_noi_that_moho_ghe_van_phong_major_8_368736be250946c19135e408e689f6c4_grande.jpg",
                "price": 1190000,
                "rating": 5,
                "reviewCount": 9,
                "boughtCount": 195,
                "discount": 37
            },
            {
                "category": "Bàn",
                "productName": "Bàn Ăn Gỗ Cao Su Tự Nhiên MOHO VLINE 601 1m6",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ban_an_go_vlne_1_28f0ed08289b49d39640efc9a9b9daab_grande.jpg",
                "price": 3790000,
                "rating": 5,
                "reviewCount": 12,
                "boughtCount": 187,
                "discount": 17
            },
            {
                "category": "Ghế",
                "productName": "Ghế Ăn Gỗ Cao Su Tự Nhiên MOHO VERONA 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_be_noi_that_moho_ghe_an_go_verona_6_8df157b011af44ca9449c3589655cde8_grande.jpg",
                "price": 1190000,
                "rating": 5,
                "reviewCount": 3,
                "boughtCount": 142,
                "discount": 40
            },
            {
                "category": "Bàn",
                "productName": "Bàn Ăn Gỗ MOHO MILAN 901 Màu Gỗ",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ban_an_go_milan_1m25_2_296dcb2c609f40ea9f3032f515910a46_grande.jpg",
                "price": 2990000,
                "rating": 5,
                "reviewCount": 9,
                "boughtCount": 190,
                "discount": 19
            },
            {
                "category": "Tủ",
                "productName": "Tủ Quần Áo Gỗ 2 Cánh MOHO VIENNA Tay Nắm 201 4 Màu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_tu_quan_ao_vienna_2_canh_5_beae67954a3643248f59f3f71fb40c11_grande.jpg",
                "price": 5990000,
                "rating": 5,
                "reviewCount": 9,
                "boughtCount": 187,
                "discount": 20
            },
            {
                "category": "Bàn",
                "productName": "Bàn Trang Điểm Gỗ Đa Năng MOHO VIENNA 202 Màu Tự Nhiên",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_combo_ban_va_guong_trang_diem_2_951e4eb74080461aa947ab14bf1a344c_grande.jpg",
                "price": 3990000,
                "rating": 5,
                "reviewCount": 19,
                "boughtCount": 179,
                "discount": 27
            },
            {
                "category": "Bộ Bàn Ăn",
                "productName": "Bộ Bàn Ăn Gỗ Cao Su Tự Nhiên MOHO VLINE 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_bo_ban_an_vline_1_d4aca5341d40427ea5531d40ad73e0ca_grande.jpg",
                "price": 5770000,
                "rating": 5,
                "reviewCount": 48,
                "boughtCount": 177,
                "discount": 34
            },
            {
                "category": "Bàn",
                "productName": "Bàn Trang Điểm Gỗ Đa Năng MOHO VIENNA 202 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_combo_ban_va_guong_trang_diem_vienna_6_0fc676db143c4193bcc6135dac83e0c0_grande.jpg",
                "price": 3990000,
                "rating": 4.8,
                "reviewCount": 5,
                "boughtCount": 163,
                "discount": 27
            },
            {
                "category": "Bàn",
                "productName": "Bàn Sofa – Bàn Cafe – Bàn Trà Gỗ Cao Su MOHO MILAN 601 Trắng",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_trang_xam_noi_that_moho_ban_sofa_verona_06_41c7041c2ef34574b8dd2242f0cee229_grande.jpg",
                "price": 590000,
                "rating": 5,
                "reviewCount": 11,
                "boughtCount": 174,
                "discount": 2
            },
            {
                "category": "Bàn",
                "productName": "Bàn Sofa – Bàn Cafe – Bàn Trà Gỗ Cao Su MOHO MILAN 602",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ban_sofa__ban_tra_go_cao_su_milan_601_3_5a7dd5037ac24566bc8fe457b7586de1_grande.jpg",
                "price": 590000,
                "rating": 5,
                "reviewCount": 4,
                "boughtCount": 178,
                "discount": 9
            },
            {
                "category": "Tủ",
                "productName": "Tủ Kệ Tivi Gỗ MOHO VLINE 301",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ke_tu_tivi_go_vline_301_1_eaa4c675e03f479d8eda5b9f5d43a221_grande.jpg",
                "price": 2990000,
                "rating": 5,
                "reviewCount": 22,
                "boughtCount": 179,
                "discount": 40
            },
            {
                "category": "Giường",
                "productName": "Giường Ngủ Gỗ Tràm MOHO HOBRO 301",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_giuong_ngu_go_hobro_7_4d7fea1dcf184dbd89fe301f120e7020_grande.jpg",
                "price": 7490000,
                "rating": 4.9,
                "reviewCount": 10,
                "boughtCount": 180,
                "discount": 32
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set 2 Bàn Sofa – Bàn Cafe – Bàn Trà Gỗ Cao Su MOHO MILAN 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_trang_xam_noi_that_moho_set_2_ban_sofa_milan_602_1_44ce4340a4764520a5754ffc2934687e_grande.jpg",
                "price": 1120000,
                "rating": 5,
                "reviewCount": 10,
                "boughtCount": 137,
                "discount": 10
            },
            {
                "category": "Ghế",
                "productName": "Ghế Sofa Góc Gỗ Cao Su Tự Nhiên MOHO VLINE 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ghe_sofa_goc_vline_dem_be_1_a901f8f89a5040b88a8bd03eed836745_grande.jpg",
                "price": 4990000,
                "rating": 5,
                "reviewCount": 5,
                "boughtCount": 145,
                "discount": 33
            },
            {
                "category": "Bộ Bàn Ăn",
                "productName": "Bộ Bàn Ăn Gỗ 4 Ghế Cao Su MOHO OSLO 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_bo_ban_an_oslo_4_ghe_oslo_9a996d424eeb437d83252f45e5152ea7_grande.jpg",
                "price": 6950000,
                "rating": 4.96,
                "reviewCount": 24,
                "boughtCount": 143,
                "discount": 44
            },
            {
                "category": "Bàn",
                "productName": "Bàn Làm Việc Gỗ Có Kệ MOHO VLINE 602 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ban_lam_viec_go_co_ke_vline_6_2fd5643fbb19409ca67f6c65a1ba77a4_grande.jpg",
                "price": 1790000,
                "rating": 5,
                "reviewCount": 16,
                "boughtCount": 139,
                "discount": 44
            },
            {
                "category": "Ghế",
                "productName": "Ghế Xoay Văn Phòng Ngả Lưng MOHO JEFE 701",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_den_noi_that_moho_ghe_van_phong_jefe_1_c22b21049a9748aa9ce64503ad45b58b_grande.jpg",
                "price": 2190000,
                "rating": 5,
                "reviewCount": 9,
                "boughtCount": 118,
                "discount": 27
            },
            {
                "category": "Giường",
                "productName": "Giường Ngủ Gỗ Tự Nhiên Mây Mắt Cáo MOHO FIJI 401",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_1m6_noi_that_moho_giuong_ngu_fiji_15_e663e013686f4676a934ed031520b8a3_grande.jpg",
                "price": 6990000,
                "rating": 5,
                "reviewCount": 9,
                "boughtCount": 133,
                "discount": 39
            },
            {
                "category": "Tủ",
                "productName": "Tủ Đầu Giường Gỗ MOHO HOBRO 301",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_dau_giuong_go_hobro_6_05dfc411382849f9b736251471040645_grande.jpg",
                "price": 2190000,
                "rating": 5,
                "reviewCount": 2,
                "boughtCount": 121,
                "discount": 27
            },
            {
                "category": "Tủ",
                "productName": "Tủ Giày - Tủ Trang Trí Gỗ MOHO VLINE 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_tu_giay_vline_601_1_8b3e99a2fffd48e08c8af6cff65d9d5a_grande.jpg",
                "price": 2490000,
                "rating": 4.69,
                "reviewCount": 16,
                "boughtCount": 112,
                "discount": 36
            },
            {
                "category": "Ghế",
                "productName": "Ghế Đôn Sofa Gỗ Cao Su Tự Nhiên MOHO VLINE 601 Màu Xám Đậm",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_ghe_don_sofa_vline_6_613d5321857749a18eb5a04daa561634_grande.jpg",
                "price": 1490000,
                "rating": 5,
                "reviewCount": 6,
                "boughtCount": 102,
                "discount": 42
            },
            {
                "category": "Ghế",
                "productName": "Ghế Sofa Góc Chữ L Gỗ Cao Su Tự Nhiên MOHO VLINE 601 Kèm Đôn",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_combo_ghe_sofa_vline_be_1_a1892ee0d68f4079b36a5a1579c15a6f_grande.jpg",
                "price": 12970000,
                "rating": 5,
                "reviewCount": 14,
                "boughtCount": 21,
                "discount": 40
            },
            {
                "category": "Bàn",
                "productName": "Bàn Làm Việc Gỗ Có Kệ MOHO VLINE 602 Màu Tự Nhiên",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_ban_lam_viec_go_co_ke_vline_4_b433c72c14024fb4b5929c24ce13509e_grande.jpg",
                "price": 1790000,
                "rating": 4.91,
                "reviewCount": 11,
                "boughtCount": 98,
                "discount": 44
            },
            {
                "category": "Ghế",
                "productName": "Ghế Sofa Gỗ Tràm Tự Nhiên MOHO VLINE 601 Màu Xám Đậm",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ghe_sofa_go_tram_vline_1_f51cf41f4609452480eb6983c9411a2f_grande.jpg",
                "price": 7490000,
                "rating": 5,
                "reviewCount": 9,
                "boughtCount": 104,
                "discount": 35
            },
            {
                "category": "Tủ",
                "productName": "Tủ Giày – Tủ Trang Trí Gỗ MOHO VIENNA 201",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_tu_giay_trang_tri_vienna_201_12_dd796a7ecf18424db966a92d3151c9ac_grande.jpg",
                "price": 1990000,
                "rating": 5,
                "reviewCount": 5,
                "boughtCount": 105,
                "discount": 43
            },
            {
                "category": "Tủ",
                "productName": "Tủ Giày – Tủ Trang Trí Gỗ MOHO VIENNA 204",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_tu_giay_trang_tri_vienna_204_8_7e15674147ae4ba08031d4c6c1fd828f_grande.jpg",
                "price": 2490000,
                "rating": 5,
                "reviewCount": 11,
                "boughtCount": 100,
                "discount": 45
            },
            {
                "category": "Kệ",
                "productName": "Kệ Để Sách 3 Tầng MOHO WORKS 703",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_trang_noi_that_moho_ke_de_sach_7_85b616ba9a054024b13dcd167096a2b4_grande.jpg",
                "price": 1390000,
                "rating": 4.9,
                "reviewCount": 10,
                "boughtCount": 111,
                "discount": 44
            },
            {
                "category": "Ghế",
                "productName": "Ghế Ăn Gỗ Cao Su Tự Nhiên MOHO MALAGA 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ghe_an_go_malaga_13_06c8020a16a14ecfae5aebf50c33ebbc_grande.jpg",
                "price": 1190000,
                "rating": 5,
                "reviewCount": 2,
                "boughtCount": 93,
                "discount": 40
            },
            {
                "category": "Tủ",
                "productName": "Tủ Quần Áo Gỗ Thanh Treo MOHO VIENNA Tay Nắm 201 4 Màu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_phoi_trang_noi_that_moho_tu_quan_ao_vienna_2_8396ce2916c443628e113ddff27172be_grande.jpg",
                "price": 3990000,
                "rating": 5,
                "reviewCount": 1,
                "boughtCount": 88,
                "discount": 11
            },
            {
                "category": "Tủ",
                "productName": "Tủ Quần Áo Gỗ Kệ Ngăn MOHO VIENNA Tay Nắm 201 4 Màu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_phoi_trang_noi_that_moho_tu_quan_ao_vienna_2_c11fd59199d442bdbea6c7b05db95a8e_grande.jpg",
                "price": 3990000,
                "rating": 5,
                "reviewCount": 1,
                "boughtCount": 88,
                "discount": 11
            },
            {
                "category": "Bàn",
                "productName": "Bàn Ăn Gỗ Cao Su Tự Nhiên MOHO VLINE 601 90cm",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ban_an_go_vline_1_9df7881d851c42c8a03db074f60690fe_grande.jpg",
                "price": 2790000,
                "rating": 5,
                "reviewCount": 5,
                "boughtCount": 95,
                "discount": 7
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set Tủ Quần Áo Gỗ MOHO VIENNA 201 4 Cánh 4 Màu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_tu_quan_ao_vienna_4_canh_1_0532c75cef6f48a680e931c3f3dc8f80_grande.jpg",
                "price": 10990000,
                "rating": 5,
                "reviewCount": 21,
                "boughtCount": 79,
                "discount": 33
            },
            {
                "category": "Bàn",
                "productName": "Bàn Sofa - Bàn Cafe - Bàn Trà Tròn Gỗ MOHO FIJI 402",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ban_tra_sofa_fiji_6_6bb71364999b4a578cc0eb3ccfeeb358_grande.jpg",
                "price": 2190000,
                "rating": 5,
                "reviewCount": 9,
                "boughtCount": 83,
                "discount": 42
            },
            {
                "category": "Bộ Bàn Ăn",
                "productName": "Bộ Bàn Ăn 4 Ghế Gỗ MOHO MILAN 901 (1m25)",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_bo_ban_an_milan_4_ghe_oslo_901_4_cebc39261df04cfa9262bdf8550c784e_grande.jpg",
                "price": 7350000,
                "rating": 5,
                "reviewCount": 21,
                "boughtCount": 82,
                "discount": 37
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set 2 Bàn Sofa – Bàn Trà Tròn Gỗ MOHO OSLO 901",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_set_ban_tra_sofa_oslo_1_f0021fb1071e4b2e9c357f2ed39539e6_grande.jpg",
                "price": 1840000,
                "rating": 5,
                "reviewCount": 5,
                "boughtCount": 84,
                "discount": 47
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set Tủ Quần Áo Gỗ MOHO VIENNA 201 2 Cánh 4 Màu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_tu_quan_ao_vienna_2_canh_noi_that_moho_3_bdde336565bc49b89effae2bb5a671a1_grande.jpg",
                "price": 6290000,
                "rating": 4.76,
                "reviewCount": 21,
                "boughtCount": 48,
                "discount": 30
            },
            {
                "category": "Bàn",
                "productName": "Bàn Ăn Gỗ Cao Su Tự Nhiên MOHO VLINE 602",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ban_an_vline_75cm_10_042d4586934f494f9f67ccea60dad0d5_grande.jpg",
                "price": 3990000,
                "rating": 5,
                "reviewCount": 4,
                "boughtCount": 69,
                "discount": 23
            },
            {
                "category": "Bộ Bàn Ăn",
                "productName": "Bộ Bàn Ăn 2 Ghế Gỗ Cao Su Tự Nhiên MOHO VLINE 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_bo_ban_an_vline_1_6d67e41e519c411f997ae51046375410_grande.jpg",
                "price": 4370000,
                "rating": 4.67,
                "reviewCount": 15,
                "boughtCount": 64,
                "discount": 37
            },
            {
                "category": "Ghế",
                "productName": "Ghế Ăn Gỗ Cao Su Tự Nhiên MOHO VIBORG 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ghe_an_go_viborg_trang_2_5efa21cd78474fd988ae3a938ac29642_grande.jpg",
                "price": 1190000,
                "rating": 5,
                "reviewCount": 3,
                "boughtCount": 59,
                "discount": 40
            },
            {
                "category": "Ghế",
                "productName": "Ghế Văn Phòng Chân Quỳ MOHO CALLOSO 701",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_den_noi_that_moho_ghe_van_phong_chan_quy_1_e2e0f1d592c34753b5c755af1444ecc2_grande.jpg",
                "price": 1090000,
                "rating": 5,
                "reviewCount": 3,
                "boughtCount": 56,
                "discount": 22
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set Tủ Quần Áo Gỗ MOHO VIENNA Tay Nắm 201 3 Cánh Kệ Ngăn",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_go_phoi_trang_noi_that_moho_tu_quan_ao_go_3_canh_vienna_1_319c205cfc4b40ca92034d7c0c92ff96_grande.jpg",
                "price": 8290000,
                "rating": 5,
                "reviewCount": 7,
                "boughtCount": 55,
                "discount": 31
            },
            {
                "category": "Bàn",
                "productName": "Bàn Sofa - Bàn Cafe - Bàn Trà Gỗ MOHO KOLDING 701",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ban_tra_sofa_kolding_1_1c8586697e0a4906a49fb4c8aa55a8a4_grande.jpg",
                "price": 2190000,
                "rating": 5,
                "reviewCount": 5,
                "boughtCount": 61,
                "discount": 39
            },
            {
                "category": "Kệ",
                "productName": "Kệ Để Sách Tủ Khóa MOHO WORKS 702",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_trang_noi_that_moho_ke_de_sach_tu_khoa_11_27da17a32ee34d3682ad2cbce1c9606a_grande.jpg",
                "price": 3190000,
                "rating": 5,
                "reviewCount": 4,
                "boughtCount": 57,
                "discount": 41
            },
            {
                "category": "Tủ",
                "productName": "Tủ Giày – Tủ Trang Trí Gỗ MOHO VIENNA 202",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_tu_giay_trang_tri_vienna_202_8_bcd6914fcfd048a7a919c1fae66f38ec_grande.jpg",
                "price": 3490000,
                "rating": 5,
                "reviewCount": 3,
                "boughtCount": 55,
                "discount": 13
            },
            {
                "category": "Tủ",
                "productName": "Tủ Gỗ Kệ Ngăn MOHO VIENNA 201 2 Màu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_trang_noi_that_moho_tu_ke_ngan_05_2dddbd16595b4d7a86f94a3044090afb_grande.png",
                "price": 2190000,
                "rating": 5,
                "reviewCount": 0,
                "boughtCount": 50,
                "discount": 45
            },
            {
                "category": "Ghế",
                "productName": "Ghế sofa góc MOHO VLINE 601 màu xám đậm",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ghe_don_sofa_vline_xam_dam_6_10e1b80fc9784af785a95d69687280ec_grande.jpg",
                "price": 4990000,
                "rating": 5,
                "reviewCount": 4,
                "boughtCount": 49,
                "discount": 33
            },
            {
                "category": "Ghế",
                "productName": "Ghế Sofa Gỗ Cao Su Tự Nhiên MOHO VLINE 601 Màu Xám Đậm",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ghe_sofa_go_vline_1_4a3275a5eb5746a99684aed9c8f60496_grande.jpg",
                "price": 7490000,
                "rating": 5,
                "reviewCount": 4,
                "boughtCount": 50,
                "discount": 35
            },
            {
                "category": "Ghế",
                "productName": "Ghế Sofa Gỗ Cao Su Tự Nhiên MOHO MOSS 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ghe_sofa_go_moss_7_341dd5d8244d4ce9a613b50684acd1fe_grande.jpg",
                "price": 10990000,
                "rating": 5,
                "reviewCount": 8,
                "boughtCount": 49,
                "discount": 29
            },
            {
                "category": "Giường",
                "productName": "Giường Ngủ Gỗ Cao Su MOHO HOBRO 301",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_giuong_ngu_go_hobro_1m6_1_37120a1d90cc4fe599d55ff8bcc57aae_grande.jpg",
                "price": 7490000,
                "rating": 5,
                "reviewCount": 7,
                "boughtCount": 53,
                "discount": 32
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set Tủ Quần Áo Gỗ MOHO VIENNA 201 3 Cánh Thanh Treo 4 Màu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_tu_quan_ao_go_3_canh_2_b0e873cfd31e48058b5702db721cb9c4_grande.jpg",
                "price": 8290000,
                "rating": 5,
                "reviewCount": 21,
                "boughtCount": 54,
                "discount": 31
            },
            {
                "category": "Bàn",
                "productName": "Bàn Làm Việc Gỗ MOHO FYN 601 Màu Tự Nhiên",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ban_hoc_lam_viec_go_fyn_1_cf383ca9c3ff43ae9dbcbda6a90550f6_grande.jpg",
                "price": 1990000,
                "rating": 5,
                "reviewCount": 10,
                "boughtCount": 73,
                "discount": 40
            },
            {
                "category": "Tủ",
                "productName": "Tủ Kệ TiVi Gỗ MOHO FIJI 401",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_ke_tivi_fiji_6_372c1b0a7a5d4624a408804cfb11a123_grande.jpg",
                "price": 3990000,
                "rating": 5,
                "reviewCount": 5,
                "boughtCount": 46,
                "discount": 37
            },
            {
                "category": "Giường",
                "productName": "Giường Ngủ Gỗ Tự Nhiên MOHO FYN 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_giuong_ngu_go_fyn_1m6_10_1666d1a167914598871d72cf8e7a1f48_grande.jpg",
                "price": 4590000,
                "rating": 5,
                "reviewCount": 3,
                "boughtCount": 38,
                "discount": 49
            },
            {
                "category": "Ghế",
                "productName": "Ghế Ăn Gỗ Cao Su Tự Nhiên MOHO SORO 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_ghe_an_go_soro_4_32d2521ecd964852a584e44bddbd29b1_grande.jpg",
                "price": 1190000,
                "rating": 5,
                "reviewCount": 1,
                "boughtCount": 71,
                "discount": 40
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set Tủ Quần Áo Gỗ MOHO VIENNA Tay Nắm 201 4 Cánh 4 Màu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_set_tu_quan_ao_go_vienna_4_canh_5_f1b27c9b507c448dad6d219b99582efb_grande.jpg",
                "price": 10990000,
                "rating": 5,
                "reviewCount": 6,
                "boughtCount": 26,
                "discount": 33
            },
            {
                "category": "Tủ",
                "productName": "Tủ Quần Áo Gỗ HOBRO 301 Kệ Ngăn",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_quan_ao_hobro_ngan_ke_57_df5a6255a3994aff9aa418b44c52d27b_grande.png",
                "price": 4290000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 29,
                "discount": 28
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set Tủ Quần Áo Gỗ MOHO VIENNA Tay Nắm 201 3 Cánh Thanh Treo",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_tu_quan_ao_go_3_canh_3_c2b0d255799a4ab3a470325643c484da_grande.jpg",
                "price": 8290000,
                "rating": 5,
                "reviewCount": 2,
                "boughtCount": 23,
                "discount": 31
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set Tủ Quần Áo Gỗ MOHO VIENNA Tay Nắm 201 2 Cánh 4 Màu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_quan_ao_2_canh_vienna_tay_nam_3_578baad5656d4beaa68027c3d7909efc_grande.jpg",
                "price": 4798000,
                "rating": 5,
                "reviewCount": 2,
                "boughtCount": 24,
                "discount": 47
            },
            {
                "category": "Tủ",
                "productName": "Tủ Kệ Tivi Gỗ MOHO ODENSE 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_cam_dat_noi_that_moho_tu_ke_tivi_go_odense_1_7e38c3d35dd0414f8d9172e3f0f1f1bf_grande.png",
                "price": 5190000,
                "rating": 5,
                "reviewCount": 1,
                "boughtCount": 20,
                "discount": 48
            },
            {
                "category": "Combo Phòng",
                "productName": "Combo Basic Phòng Ngủ Grenaa 201 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_nau_noi_that_grenaa_moho__7__69d231891277473fbe532e1af7244cbb_grande.jpg",
                "price": 5080000,
                "rating": 5,
                "reviewCount": 2,
                "boughtCount": 27,
                "discount": 33
            },
            {
                "category": "Bàn",
                "productName": "Bàn Sofa – Bàn Cafe – Bàn Trà Gỗ MOHO ODENSE 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_cam_dat_noi_that_moho_ban_tra_sofa_go_odense_1_b8c62f429bb84917afcf77459cccc545_grande.jpg",
                "price": 5090000,
                "rating": 5,
                "reviewCount": 2,
                "boughtCount": 16,
                "discount": 22
            },
            {
                "category": "Tủ",
                "productName": "Tủ Kệ Tivi Gỗ MOHO KOLDING 702",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_ke_tivi_kolding_1_85628cac95344a59bcf705e71eaf7a36_grande.jpg",
                "price": 4190000,
                "rating": 5,
                "reviewCount": 2,
                "boughtCount": 16,
                "discount": 35
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full Combo Phòng Ngủ Ubeda 201 Màu Tự Nhiên",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_full_combo_phong_ngu_ubeda_1_243030d159134a0aac4c2c65c5bda938_grande.jpg",
                "price": 10960000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 20,
                "discount": 33
            },
            {
                "category": "Tủ",
                "productName": "Tủ Quần Áo Gỗ HOBRO 301 Thanh Treo",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_quan_ao_hobro_thanh_treo_16_548b78107c5440aaa76b11be1c015b6e_grande.png",
                "price": 4290000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 30,
                "discount": 28
            },
            {
                "category": "Bộ Bàn Ăn",
                "productName": "Bộ Bàn Ăn Gỗ 6 Ghế Cao Su MOHO OSLO 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_bo_ban_an_oslo_6_ghe_oslo_1_054e2af61f224796aba9656935051e34_grande.jpg",
                "price": 8930000,
                "rating": 5,
                "reviewCount": 13,
                "boughtCount": 13,
                "discount": 46
            },
            {
                "category": "Combo Phòng",
                "productName": "Combo Basic Phòng Ăn Ubeda 201 Màu Tự Nhiên",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_combo_basic_phong_an_ubeda_2_bba57728e757449f90861373bd3ce8be_grande.jpg",
                "price": 5350000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 19,
                "discount": 31
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full Combo Phòng Ngủ Grenaa 201 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_full_combo_4_mon_noi_that_grenaa_moho__46__3eb1628e11c447d08bf81ff202bd9fe8_grande.jpg",
                "price": 12060000,
                "rating": 5,
                "reviewCount": 2,
                "boughtCount": 17,
                "discount": 33
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full Combo Phòng Khách MOHO KOSTER Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/o_nau_noi_that_moho_full_combo_phong_khach_moho_koster_mau_nau__23415__83c6ed699b72450ab7753785432d5c62_grande.jpg",
                "price": 10960000,
                "rating": 5,
                "reviewCount": 2,
                "boughtCount": 12,
                "discount": 34
            },
            {
                "category": "Bàn",
                "productName": "Bàn Ăn Gỗ Tràm Tự Nhiên MOHO NYBORG 301",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_den_noi_that_moho_ban_an_go_nyborg_5_0dddf596994f443c8b575cfe573afc61_grande.jpg",
                "price": 3490000,
                "rating": 5,
                "reviewCount": 2,
                "boughtCount": 12,
                "discount": 42
            },
            {
                "category": "Bộ Bàn Ăn",
                "productName": "Bộ Bàn Ăn Gỗ Cao Su Tự Nhiên MOHO VLINE 602 (75cm)",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_bo_ban_an_vline_4_ghe_odessa_1_f454ff9a7c594124a385d1f0a7236ee5_grande.jpg",
                "price": 7150000,
                "rating": 5,
                "reviewCount": 6,
                "boughtCount": 17,
                "discount": 46
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full House Bộ Sưu Tập Grenaa 201 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_nau_noi_that_grenaa_moho__17__d497024658fd44958d4c87aaf3ed4da2_grande.jpg",
                "price": 22770000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 9,
                "discount": 36
            },
            {
                "category": "Ghế",
                "productName": "Ghế Sofa MOHO LEEDS 701",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_xanh_duong_noi_that_moho_ghe_sofa_go_leeds_5_717684bef5cf493db5d7edf78d315fd5_grande.jpg",
                "price": 9990000,
                "rating": 5,
                "reviewCount": 1,
                "boughtCount": 9,
                "discount": 36
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set Tủ Quần Áo Gỗ MOHO HOBRO 301 4 Cánh",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_quan_ao_hobro_4_canh_2m_2_fa93cf40bd4d4daaa3fb8408a2a1281b_grande.png",
                "price": 13990000,
                "rating": 5,
                "reviewCount": 2,
                "boughtCount": 13,
                "discount": 39
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set Tủ Quần Áo Gỗ MOHO HOBRO 301 2 Cánh",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_quan_ao_hobro_2_canh_1m_20_2362be8605d8485b95efeffc54e3b447_grande.png",
                "price": 6990000,
                "rating": 5,
                "reviewCount": 1,
                "boughtCount": 10,
                "discount": 42
            },
            {
                "category": "Combo Phòng",
                "productName": "Combo Basic Phòng Ngủ MOHO KOSTER Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_combo_bs_1_noi_that_moho_koster_9017545cd40c40938f498a421ad6f8b4_grande.jpg",
                "price": 6880000,
                "rating": 5,
                "reviewCount": 1,
                "boughtCount": 11,
                "discount": 33
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full Combo Phòng Khách Narvik 201 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_nau_noi_that_moho_narvik_livingroom_full_d817b1f747df4c088f3aac13a135a875_grande.jpg",
                "price": 8660000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 7,
                "discount": 34
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full Combo Phòng Khách Grenaa 201 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_nau_noi_that_grenaa_moho__26__25945458ba02412192ab68c2c04cb81e_grande.jpg",
                "price": 7460000,
                "rating": 5,
                "reviewCount": 1,
                "boughtCount": 11,
                "discount": 32
            },
            {
                "category": "Tủ",
                "productName": "Tủ Kệ Tivi Gỗ MOHO LEEDS 701",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_go_phoi_den_noi_that_moho_tu_ke_tivi_leeds_9_1c34f9c4f4db42538bef96a6d18e6790_grande.jpg",
                "price": 4490000,
                "rating": 5,
                "reviewCount": 1,
                "boughtCount": 7,
                "discount": 25
            },
            {
                "category": "Combo Phòng",
                "productName": "Combo Phòng Ăn MOHO KOSTER Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_combo_phong_an_moho_koster_mau_nau_444_69fba7541b9d43ac9d6459bb7cb6f4eb_grande.jpg",
                "price": 7350000,
                "rating": 5,
                "reviewCount": 2,
                "boughtCount": 11,
                "discount": 33
            },
            {
                "category": "Ghế",
                "productName": "Ghế Sofa Gỗ Cao Su Tự Nhiên MOHO FREDERICIA 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_xanh_duong_noi_that_moho_ghe_sofa_go_fredercia_2_ee9c691e9d694d4db7627ecd10c747ef_grande.jpg",
                "price": 8490000,
                "rating": 5,
                "reviewCount": 1,
                "boughtCount": 5,
                "discount": 41
            },
            {
                "category": "Ghế",
                "productName": "Ghế Đôn Sofa Gỗ Tràm Tự Nhiên MOHO KOLDING 701",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ghe_don_sofa_kolding_701_1_32d14bd4bc0c4d3586ca2560723d7da8_grande.jpg",
                "price": 2190000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 9,
                "discount": 37
            },
            {
                "category": "Ghế",
                "productName": "Ghế Đôn Sofa Gỗ Cao Su Tự Nhiên MOHO FYN 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/noi-that-moho-ghe-don-sofa-fyn-601-bo-ban-ghe_e3416720f77d4e12a1acad36d44c2ff0_grande.jpg",
                "price": 1990000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 8,
                "discount": 43
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full House (Combo Basic) Bộ Sưu Tập Grenaa 201 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_nau_noi_that_grenaa_moho__22__a76dca50353447dca2b62c36fe02f47f_grande.jpg",
                "price": 14600000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 6,
                "discount": 36
            },
            {
                "category": "Combo Phòng",
                "productName": "Combo Basic Phòng Khách Narvik 201 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_nau_noi_that_moho_narvik_livingroom_basic_1_89ac244d12b6487c9191f26d359302f3_grande.jpg",
                "price": 6670000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 7,
                "discount": 34
            },
            {
                "category": "Ghế",
                "productName": "Ghế Sofa Gỗ Cao Su Tự Nhiên MOHO TROMSO 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_den_noi_that_moho_ghe_sofa_go_tromso_ba9591dc9737442cbd9733f4538c8268_grande.jpg",
                "price": 10990000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 6,
                "discount": 44
            },
            {
                "category": "Set Tủ / Bàn",
                "productName": "Set Tủ Quần Áo Gỗ MOHO HOBRO 301 3 Cánh Thanh Treo",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_tu_quan_ao_hobro_3_canh_1m5_8_3219fa946ce34d74ba14e9f30a277c74_grande.png",
                "price": 10490000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 7,
                "discount": 38
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full Combo Phòng Khách Ubeda 201 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_nau_noi_that_moho_ubeda_livingroom_a4a14b63e87d4d0486eefd7402dbf9bd_grande.jpg",
                "price": 8660000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 6,
                "discount": 35
            },
            {
                "category": "Bàn",
                "productName": "Bàn Sofa - Bàn Cafe - Bàn Trà Gỗ MOHO HOBRO 601",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_ban_tra_sofa_go_hobro_7_9766a2a8c7ad4e848b65f91994b39f65_grande.jpg",
                "price": 2190000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 7,
                "discount": 31
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full House Bộ Sưu Tập Narvik 201 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_nau_noi_that_moho_narvik_livingroom_full_04c13065d93a456ebf817275c8c54780_grande.jpg",
                "price": 23170000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 2,
                "discount": 36
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full Combo Phòng Khách Narvik 201 Màu Tự Nhiên",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_full_combo_narvik__1__dbf183ed714f46968999199979123ba2_grande.jpg",
                "price": 8760000,
                "rating": 5,
                "reviewCount": 3,
                "boughtCount": 6,
                "discount": 33
            },
            {
                "category": "Combo Phòng",
                "productName": "Combo Basic Phòng Ngủ MOHO LANGO Màu Nâu Cam",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_noi_that_moho_combo_bs_1_lango_mau_nau__11__1998f30489954abcb7518e5dbd3ac31f_grande.jpg",
                "price": 9480000,
                "rating": 4,
                "reviewCount": 1,
                "boughtCount": 3,
                "discount": 40
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full House (Combo Basic) Bộ Sưu Tập Narvik 201 Màu Tự Nhiên",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_combo_narvik_coohom__25__9db84ca5bfe3493b99293aba2f246698_grande.jpg",
                "price": 15300000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 1,
                "discount": 36
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full House (Combo Basic) Bộ Sưu Tập Ubeda 201 Màu Tự Nhiên",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_tu_nhien_noi_that_moho_full_house_ubeda_1_4a27b73a83db4ff39385fa7abebb2c3c_grande.jpg",
                "price": 16500000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 1,
                "discount": 35
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full House (Combo Basic) MOHO LANGO Màu Nâu Cam",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_noi_that_moho_combo_bs_1_mau_nau__25__cd4a796d48fe4b378981d00ae7d2eadd_grande.jpg",
                "price": 23600000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 0,
                "discount": 41
            },
            {
                "category": "Combo Phòng",
                "productName": "Combo Phòng Ăn MOHO LANGO Màu Nâu Cam",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_nau_noi_that_moho_combo_phong_an_lango_mau_nau__2__9868ce937af6489092b46a4b9fdb7c67_grande.jpg",
                "price": 5250000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 5,
                "discount": 39
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full House (Combo Basic) Bộ Sưu Tập Narvik 201 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_nau_noi_that_moho_narvik__5__cfebcbd0fe564a7187e8566ba0c5af5e_grande.jpg",
                "price": 15300000,
                "rating": 0,
                "reviewCount": 0,
                "boughtCount": 0,
                "discount": 36
            },
            {
                "category": "Full House / Combo Phòng",
                "productName": "Full House (Combo Basic) Bộ Sưu Tập Ubeda 201 Màu Nâu",
                "thumbnail": "https://product.hstatic.net/200000065946/product/pro_mau_nau_noi_that_moho_ubeda__6__61e1e0901d40426bae3d8e731496eeba_grande.jpg",
                "price": 16500000,
                "rating": 5,
                "reviewCount": 1,
                "boughtCount": 1,
                "discount": 35
            }
        ] 

        category_dict = {}
        for data in product_data:
            category_name = data['category']
            if category_name not in category_dict:
                category, created = Category.objects.get_or_create(
                    name=category_name,
                    defaults={
                        'slug': category_name.lower().replace(' ', '-'),
                        'icon_url': 'https://example.com/default-icon.jpg',
                        'created_at': timezone.now(),
                        'updated_at': timezone.now(),
                        'deleted_at': None
                    }
                )
                category_dict[category_name] = category
            else:
                category = category_dict[category_name]
        
        for data in product_data:
            category_name = data['category']
            product_name = data['productName']
            thumbnail = data['thumbnail']
            price = data['price']
            discount = data['discount']

            category = category_dict.get(category_name)
            
            Product.objects.create(
                        name=product_name,
                        unit='pcs',
                        price=price,
                        discount = discount,
                        amount = 1,
                        is_public = True,
                        category_id=category,
                        thumbnail = thumbnail,
                        created_at=timezone.now(),
                        updated_at=timezone.now(),
                        deleted_at=timezone.now()
                    )
    operations = [
        migrations.RunPython(create_default_data),
    ]

